### ISSUE TITLE
May need some Transit encoding/decoding

### ISSUE THREAD

**Issue by eoliphan** [wilkerlucio/pathom-datomic#2]
Trying to explore an index with this plugin enabled causes the following

```
java.lang.RuntimeException: java.lang.Exception: Not supported: class com.wsscode.pathom.connect.datomic$index_schema$fn__33635
	at com.cognitect.transit.impl.WriterFactory$1.write(WriterFactory.java:65)
	at cognitect.transit$write.invokeStatic(transit.clj:167)
	at cognitect.transit$write.invoke(transit.clj:164)
	at com.fulcrologic.fulcro.server.api_middleware$write.invokeStatic(api_middleware.clj:150)
	at com.fulcrologic.fulcro.server.api_middleware$write.invoke(api_middleware.clj:147)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:667)
	at clojure.core$update_in$up__6853.invoke(core.clj:6185)
	at clojure.core$update_in.invokeStatic(core.clj:6186)
	at clojure.core$update_in.doInvoke(core.clj:6172)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at com.fulcrologic.fulcro.server.api_middleware$wrap_transit_response$fn__32543.invoke(api_middleware.clj:168)
	at fm.server_components.middleware$wrap_html_routes$fn__37465.invoke(middleware.clj:105)
	at ring.middleware.anti_forgery$wrap_anti_forgery$fn__34825.invoke(anti_forgery.clj:94)
	at ring.middleware.session$wrap_session$fn__34491.invoke(session.clj:108)
	at ring.middleware.keyword_params$wrap_keyword_params$fn__34605.invoke(keyword_params.clj:53)
	at ring.middleware.nested_params$wrap_nested_params$fn__34663.invoke(nested_params.clj:89)
	at ring.middleware.multipart_params$wrap_multipart_params$fn__34911.invoke(multipart_params.clj:173)
	at ring.middleware.params$wrap_params$fn__34935.invoke(params.clj:67)
	at ring.middleware.cookies$wrap_cookies$fn__34370.invoke(cookies.clj:214)
	at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__35077.invoke(absolute_redirects.clj:47)
	at ring.middleware.resource$wrap_resource_prefer_resources$fn__34156.invoke(resource.clj:25)
	at ring.middleware.content_type$wrap_content_type$fn__35025.invoke(content_type.clj:34)
	at ring.middleware.default_charset$wrap_default_charset$fn__35049.invoke(default_charset.clj:31)
	at ring.middleware.not_modified$wrap_not_modified$fn__34991.invoke(not_modified.clj:61)
	at ring.middleware.x_headers$wrap_x_header$fn__34522.invoke(x_headers.clj:22)
	at ring.middleware.x_headers$wrap_x_header$fn__34522.invoke(x_headers.clj:22)
	at ring.middleware.ssl$wrap_hsts$fn__35114.invoke(ssl.clj:105)
	at ring.middleware.gzip$wrap_gzip$fn__35193.invoke(gzip.clj:100)
	at org.httpkit.server.HttpHandler.run(RingHandler.java:115)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Exception: Not supported: class com.wsscode.pathom.connect.datomic$index_schema$fn__33635
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:194)
	at com.cognitect.transit.impl.JsonEmitter.emitMap(JsonEmitter.java:171)
	at com.cognitect.transit.impl.AbstractEmitter.emitMap(AbstractEmitter.java:85)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:184)
	at com.cognitect.transit.impl.AbstractEmitter.emitArray(AbstractEmitter.java:97)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:182)
	at com.cognitect.transit.impl.AbstractEmitter.emitArray(AbstractEmitter.java:97)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:182)
	at com.cognitect.transit.impl.JsonEmitter.emitMap(JsonEmitter.java:171)
	at com.cognitect.transit.impl.AbstractEmitter.emitMap(AbstractEmitter.java:85)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:184)
	at com.cognitect.transit.impl.JsonEmitter.emitMap(JsonEmitter.java:171)
	at com.cognitect.transit.impl.AbstractEmitter.emitMap(AbstractEmitter.java:85)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:184)
	at com.cognitect.transit.impl.AbstractEmitter.emitArray(AbstractEmitter.java:97)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:182)
	at com.cognitect.transit.impl.AbstractEmitter.emitTagged(AbstractEmitter.java:49)
	at com.cognitect.transit.impl.AbstractEmitter.emitEncoded(AbstractEmitter.java:74)
	at com.cognitect.transit.impl.AbstractEmitter.marshal(AbstractEmitter.java:187)
	at com.cognitect.transit.impl.AbstractEmitter.marshalTop(AbstractEmitter.java:211)
	at com.cognitect.transit.impl.JsonEmitter.emit(JsonEmitter.java:41)
	at com.cognitect.transit.impl.WriterFactory$1.write(WriterFactory.java:62)
	... 35 more
```

**Comment by wilkerlucio** [comment]
I documented how to handle those transit issues at:

https://wilkerlucio.github.io/pathom/v2/pathom/2.2.0/connect/exploration.html#_fixing_transit_encoding_issues

**Comment by eoliphan** [comment]
ah heck lol
